- name: Install and Configure Webservers.
  hosts: all
  gather_facts: false
  tasks:
    - name: Install HTTPD package
      dnf:
        name: httpd
        state: latest

    - name: Enable HTTPD Service
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: Deploy content to webservers
      template:
        src: template/index.html.j2
        dest: /var/www/html/index.html
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
   
